/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.hw2;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class PeerView2 extends javax.swing.JFrame {

    /**
     * Creates new form PeerView2
     */
   DatagramSocket DS;
   
    int port;
    DatagramPacket msg;

    Thread thread;
     byte [] Bmsg = new byte[1024];
    
    /**
     * Creates new form PeerView
     */
    public PeerView2() {
        initComponents();
    /*   thread = new Thread(){
        public void run(){

           while(true){
                try {
                     System.out.println("hey");
                   Bmsg = new byte[1024];
                     DatagramPacket receivedPacket=new DatagramPacket(Bmsg,Bmsg.length);
                     DS.receive(receivedPacket);
                     String newsen=new String(receivedPacket.getData());
                     chat1.append(newsen+"\n");
                     
                } 
                catch (Exception ex) {
                     System.out.println("Shit");
                  //  JOptionPane.showMessageDialog(null,"BAD","OK",JOptionPane.INFORMATION_MESSAGE);
                }

            }
        }
        };

        thread.start(); */
    }
                                      
        
    
         
         
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connect = new javax.swing.JButton();
        send = new javax.swing.JButton();
        SIP = new javax.swing.JTextField();
        SP = new javax.swing.JTextField();
        RIP = new javax.swing.JTextField();
        RP = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        sentMsg = new javax.swing.JTextField();
        chat = new javax.swing.JScrollPane();
        chat1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));

        connect.setText("Connect");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        send.setText("Send !");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        SIP.setMinimumSize(new java.awt.Dimension(100, 100));

        SP.setMinimumSize(new java.awt.Dimension(100, 100));

        RIP.setMinimumSize(new java.awt.Dimension(100, 100));

        RP.setMinimumSize(new java.awt.Dimension(150, 200));

        name.setToolTipText("");
        name.setMinimumSize(new java.awt.Dimension(150, 200));

        chat1.setColumns(20);
        chat1.setRows(5);
        chat.setViewportView(chat1);

        jLabel1.setText("Sender IP:");

        jLabel2.setText("Sender Port:");

        jLabel3.setText("Receiver IP:");

        jLabel4.setText("Receiver Port:");

        jLabel5.setText("Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sentMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chat, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RIP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SIP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chat, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(10, 10, 10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sentMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
       try {
             
             int ReP=Integer.parseInt(RP.getText());
            InetAddress ip=InetAddress.getByName(this.RIP.getText());
            String m=name.getText()+" : "+sentMsg.getText();
            DatagramPacket sendPacket=new DatagramPacket(m.getBytes(),m.length(),ip,ReP);
             DS.send(sendPacket);
             chat1.append(m+"\n");
             sentMsg.setText("");
              
         }
         catch (Exception e){
             System.out.print("two"); //JOptionPane.showMessageDialog(null,"BAD","OK",JOptionPane.INFORMATION_MESSAGE);
         }
     
    }//GEN-LAST:event_sendActionPerformed

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
     
          try {
                int x=Integer.parseInt(SP.getText());
                InetAddress y=InetAddress.getByName(this.SIP.getText());
                DS=new DatagramSocket(x,y);
                thread = new Thread(){
        public void run()
        {
System.out.println("hey");
            while(true){
                try {
                     
                     Bmsg = new byte[1024];
                     DatagramPacket receivedPacket=new DatagramPacket(Bmsg,Bmsg.length);
                     DS.receive(receivedPacket);
                     String newsen=new String(receivedPacket.getData());
                     chat1.append(newsen+"\n");
                     
                } 
                catch(Exception e){
                    System.out.print("one");
                }
    

            }
        }
        };

        thread.start();
        JOptionPane.showConfirmDialog(this,"good");
        
        
       
                }
          catch (Exception e){
              System.out.println("Shit");
          }
     
     
    }//GEN-LAST:event_connectActionPerformed

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField RIP;
    public javax.swing.JTextField RP;
    public javax.swing.JTextField SIP;
    public javax.swing.JTextField SP;
    private javax.swing.JScrollPane chat;
    private javax.swing.JTextArea chat1;
    public javax.swing.JButton connect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField name;
    public javax.swing.JButton send;
    public javax.swing.JTextField sentMsg;
    // End of variables declaration//GEN-END:variables
}
